#![recursion_limit = "256"]

// Required by code generated by the upstream `#[instrument]` macro.
extern crate miden_node_tracing as tracing;
use std::num::NonZeroUsize;
use std::time::Duration;

#[cfg(test)]
pub mod test_utils;

mod batch_builder;
mod block_builder;
mod block_prover;
mod domain;
mod fee_collector;
mod mempool;
mod proof_scheduler;
mod rpc_sync;
pub mod store;
mod validator;

#[cfg(feature = "testing")]
pub mod errors;
#[cfg(not(feature = "testing"))]
mod errors;

pub mod server;
pub use domain::transaction::ensure_transaction_has_fee;
pub use errors::MempoolSubmissionError;
pub use fee_collector::deploy_fee_collector;
pub use proof_scheduler::DEFAULT_MAX_CONCURRENT_PROOFS;
pub use rpc_sync::{RpcReadiness, RpcSync};
pub use server::{
    BlockProducerApi,
    BlockProducerApiConfig,
    BlockProducerStatus,
    MempoolStats,
    Sequencer,
    SequencerHandle,
};

// CONSTANTS
// =================================================================================================

/// The name of the block producer component.
pub const COMPONENT: &str = "miden-block-producer";

/// The tracing target used for stdout-visible events.
pub const LOG_TARGET: &str = "user::miden-block-producer";

/// The number of transactions per batch.
pub const DEFAULT_MAX_TXS_PER_BATCH: NonZeroUsize = NonZeroUsize::new(8).unwrap();

/// Maximum number of batches per block.
pub const DEFAULT_MAX_BATCHES_PER_BLOCK: NonZeroUsize = NonZeroUsize::new(8).unwrap();

/// Default size of the batch-builder worker pool.
///
/// Each worker can prove one batch at a time. Raising this allows more
/// concurrent batch proofs in-flight, which is the primary lever for lifting
/// the per-block-producer TPS ceiling once `--max-txs-per-batch` and
/// `--max-batches-per-block` are pushed up.
pub const DEFAULT_BATCH_WORKERS: NonZeroUsize = NonZeroUsize::new(2).unwrap();

/// The number of blocks of committed state that the mempool retains.
///
/// This determines the grace period incoming transactions have between fetching their input from
/// the store and verification in the mempool.
const SERVER_MEMPOOL_STATE_RETENTION: NonZeroUsize = NonZeroUsize::new(5).unwrap();

/// Transactions are rejected by the mempool if there is less than this amount of blocks between the
/// chain tip and the transaction's expiration block.
///
/// This rejects transactions which would likely expire before making it into a block.
const SERVER_MEMPOOL_EXPIRATION_SLACK: u32 = 2;

/// The interval at which to update the cached mempool statistics.
const CACHED_MEMPOOL_STATS_UPDATE_INTERVAL: Duration = Duration::from_secs(5);

/// How often a block is created.
pub const DEFAULT_BLOCK_INTERVAL: Duration = Duration::from_secs(3);

/// Maximum interval between batch scheduler checks.
pub const DEFAULT_BATCH_INTERVAL: Duration = Duration::from_secs(1);

/// The request timeout for the sequencer's `sign_block` call to the validator.
///
/// This bounds the wait to a fast, retryable error while leaving ample headroom above normal
/// `sign_block` latency.
pub const DEFAULT_VALIDATOR_TIMEOUT: Duration = Duration::from_secs(30);

/// The default transaction capacity of the mempool.
///
/// The value is selected such that all transactions should approximately be processed within one
/// minutes with a block time of 5s.
#[expect(clippy::cast_sign_loss, reason = "Both durations are positive")]
pub const DEFAULT_MEMPOOL_TX_CAPACITY: NonZeroUsize = NonZeroUsize::new(
    DEFAULT_MAX_BATCHES_PER_BLOCK.get()
        * DEFAULT_MAX_TXS_PER_BATCH.get()
        * (Duration::from_mins(1).div_duration_f32(DEFAULT_BLOCK_INTERVAL)) as usize,
)
.unwrap();

const _: () = assert!(
    DEFAULT_MAX_BATCHES_PER_BLOCK.get() <= miden_protocol::MAX_BATCHES_PER_BLOCK,
    "Server constraint cannot exceed the protocol's constraint"
);

const _: () = assert!(
    DEFAULT_MAX_TXS_PER_BATCH.get() <= miden_protocol::MAX_ACCOUNTS_PER_BATCH,
    "Server constraint cannot exceed the protocol's constraint"
);
